server:
  port: 8088
spring:
  application:
    name: springcloud-sentinel-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.130:8848
        enabled: true
    sentinel:
      transport:
        port: 8719 #跟控制台交流的端口
        dashboard: localhost:8080 # 指定控制台服务的地址
      eager: off
  #      datasource:
#        flow:
#          nacos:
#            server-addr: 192.168.5.130:8848 #nacos的服务注册中心
#            data-id: account-sentinel.json #这是唯一的数据id
#            group-id: DEFAULT_GROUP  #nacos配置中心的组id
#            rule-type: flow #规则为限流
  #配置数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.5.130:3306/seata_order
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间(毫秒)
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
      filters: stat, wall, log4j
      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml